### ISSUE TITLE
bug: Certificate has expired

### ISSUE THREAD

**Issue by KibaNoOu** [quanglam2807/webcatalog#1532] opened 2021-09-30 19:36 UTC
# Bug Report
**Specifications:**
- WebCatalog Version: Version v37.2.1 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Windows

**Description:**
When i try to update any application i get a Failed error, certificate has expired

**Steps to Reproduce:**
Update any application

**Additional Context**
![immagine](https://user-images.githubusercontent.com/11923117/135519259-1798576a-e4ac-49e7-90b9-b358ca18da46.png)

**Comment by quanglam2807** [comment] 2021-09-30 20:56
Thanks for reporting. This likely happens because of DNS outage happening today (https://www.theverge.com/2021/9/30/22702876/slack-is-down-outage-morning-disruption-work-chat). We've issued a fix for this in v37.3.0.

**Closed as completed by quanglam2807** 2021-09-30 20:56 UTC
Labels: bug

**Comment by quanglam2807** [comment] 2021-09-30 22:44
Found the cause: https://github.com/electron/electron/pull/31213
