### ISSUE TITLE
bug: Installed apps don't open.

### ISSUE THREAD

**Issue by IgorIzyurov** [quanglam2807/webcatalog#1558] opened 2021-11-04 05:11 UTC
# Bug Report
**Specifications:**
- WebCatalog Version: 39.0.1 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Pop OS 21.04
- Gnome 3.38.5, windowing system X11

**Description:**
Clicking [OPEN] button on a pictogram of an installed app doesn't  result in any action, except button click animation. Console also shows no prompt.
The behavior is observed when trying to start any app in 'Catalog' tab, 'Installed' tab or in 'Details' window. 
Running WebCatalog with various preferences didn't help (tried: changing Theme, Use system title bar and borders on/off, Hardware acceleration on/off, Show tray icon  on/off, Pin window to system tray  on/off)

**Steps to Reproduce:**
Download WebCatalog-39.0.1.AppImage for x64 linux from the official website, run on Pop OS 21.04

**Additional Context**
Could the observed behavior be related to permissions or OS window settings, that prevent opening separate windows?

https://user-images.githubusercontent.com/56837204/140262210-fab3b911-a15c-46fb-9ef5-fd3e8c4a51ab.mp4

**Comment by quanglam2807** [comment] 2021-11-06 22:01
I'll try to get this fixed soon. I couldn't reproduce the bug on Ubuntu so it's probably related to Pop! OS.

**Comment by quanglam2807** [comment] 2021-11-07 01:24
I gave up! Somehow this line of code doesn't work on PopOS: https://github.com/webcatalog/webcatalog-app/blob/master/main-src/libs/app-management/open-app.js#L16

The command works if it is triggered directly in Terminal but somehow it doesn't work inside the app. You can launch the installed apps from PopOS application list for now. :(

**Comment by quanglam2807** [comment] 2021-11-07 01:27
The command returns no error so it is triggered successfully but refuses to open the app.

**Comment by insolite** [comment] 2021-11-11 07:18
I'm having the same in Arch Linux + XFCE. `gtk-launch *.desktop` works just fine from the terminal as well as running it from XFCE UI launcher or using xdg-open. But not from webcatalog UI.

I guess the reason is the environment (variable), so that `gtk-launch` can't find the `*.desktop` file. Probably `XDG_DATA_HOME` is set incorrectly or something like that.

**Comment by quanglam2807** [comment] 2021-11-13 14:00
From my test, it seems like `gtk-launch` does manage to find the `*.desktop` file as it does return errors if the name of the desktop file is incorrect. The command triggers successfully but doesn't do anything.

**Comment by madroots** [comment] 2021-11-28 19:58
same here, Zorin OS, basically ubuntu 18 :/

**Comment by TungDo-WFG** [comment] 2021-12-15 03:59
Same for me, Ubuntu 20.04. Clicking Open button does nothing
Edit: After installing Chatwork, I can see the app in Ubuntu's app list (Pressing Windows key). Opening it manually works well, but open it through Web Catalog does not.

**Comment by Timo-Hoyland** [comment] 2021-12-27 07:05
I have come across the same issue on Kali Linux aswell. It's a shame really; it sounds really promising. I hope it gets fixed soon

**Comment by bschelst** [comment] 2022-01-03 21:00
Same on Neon (ubuntu 20.04 based)

**Comment by quanglam2807** [comment] 2022-02-04 01:36
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.

**Closed as completed by quanglam2807** 2022-02-04 01:36 UTC
Labels: bug
