### ISSUE TITLE
bug:  Microsoft Office/Teams Multi Factor Authentication (Mobile App)

### ISSUE THREAD

**Issue by JasonCraneAdkins** [quanglam2807/webcatalog#1577] opened 2021-12-02 10:21 UTC
# Bug Report
**Specifications:**
- WebCatalog Version: Version v40.2.0 (x64)
- Neutron Version: ?
- OS: Windows

**Description:**
When logging in with a Business Account and Two-Factor Authentication to Microsoft Office (*.office.com) and/or Microsoft Teams (Teams.microsoft.com), a message appears in the Authentificator App (iOS/Android) after entering the user and password.
After confirming this message, the login continues.

**Steps to Reproduce:**
In the WebCatalog, it stops without a message after the user and password is entered.
(After pressing "Sign in", there is no reaction).

**Additional Context**
There is no indication of a login in the linked Authenticator app.

**Comment by jaseerabubakar** [comment] 2021-12-02 17:14
I have the same issue. A lot of my usage (webcatalog lifetime) is around microsoft services. So this really broke everything for me

**Comment by quanglam2807** [comment] 2021-12-02 19:36
Founder here.

Currently, Google login is broken as well. I'll try to fix these issues as soon as I can.

I hope we'd be able to figure out a solution soon.

**Comment by quanglam2807** [comment] 2021-12-02 21:25
The bug is likely fixed with Neutron 21.6.3. Can you guys give it a try?

**Comment by jaseerabubakar** [comment] 2021-12-03 08:21
i cant reproduce the issue anymore although the webcatalog version is still v40.2.0 (x64)
Is it possible the neutron engine has been updated automatically. I don't build it myself, I use the executables from the website.

**Comment by JasonCraneAdkins** [comment] 2021-12-03 09:28
Problem is fixed, it works as I imagine.

I am pleasantly surprised that the problem was fixed so quickly.
If I understand it correctly, it was related to the Neutron update that was rolled out independently of my problem.

My problem is solved, I don't care how. Since it happened so quickly it is worth a license to me.
Just bought the lifetime license.

Thanks a lot!

**Comment by quanglam2807** [comment] 2021-12-03 23:32
@JasonCraneAdkins That's great! Thank you so much for supporting us!

@jaseerabubakar The apps you install are powered by Neutron, which is updated separately from the WebCatalog app.

**Closed as completed** 2021-12-03 23:38 UTC
Labels: bug
